### ISSUE TITLE
Provision frontend and middle tier for data slice tenant

### ISSUE THREAD

**Issue by gigamorph** [project-lux/lux-middletier#57]
**Problem Description:**
Create new frontend and middle tier components to work with the "data slice" tenant of MarkLogic.

**Requirements:**
- No need for CloudFront and web cache
- Single environment (DEV)

**Tasks:**
- Provision via Terraform:
  - [x] Load balancer that routes between frontend and middle tier
  - [x] Frontend (Fargate)
  - [x] Middle tier (Fargate)
- Add Jenkins jobs:
  - [x] Frontend
  - [x] Middle tier
- [x] Get domain name - lux-byunit.collections.yale.edu
